### ISSUE TITLE
INVALID_CLIENT: Invalid client

### ISSUE THREAD

**Issue by kana7577** [jonashcroft/Nowify#12]
INVALID_CLIENT: Invalid clientt
If you click on Login with Spotify　you will see this.

What are Redirect URIs?

**Comment by jonashcroft** [comment]
When you create a new client in the Spotify Dashboard, you add in a Redirect URI here. This is essentially the URL of your app. It'll be something like 'http://localhost:8080' or 'https://myurl.com' - depending on what you're doing. It's the URL for your Spotify client to redirect back to when the user logs in.

You're right that I forgot to add this into the README, I'll add it in.

Read the Spotify docs:
[https://developer.spotify.com/documentation/general/guides/app-settings/](https://developer.spotify.com/documentation/general/guides/app-settings/)

**Comment by kana7577** [comment]
localhost&myurlI tried both. It didn't work.
Do you have a solution for me?

**Comment by kana7577** [comment]
Sorry, I didn't check.
The url was wrong.

**Comment by jonashcroft** [comment]
Great! Glad you got it.
