### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by johnkareoke** [jonashcroft/Nowify#2]
Really nice looking piece of work Jonashcroft!

Can't seem to get this to work:

I've updated my client ID and Secret as well as whitelisted my URL and repeatedly get the same error:

"INVALID_CLIENT: Invalid redirect URI"

Any assistance would be much appreciated.

**Comment by clancyjr** [comment]
same problem. I went back to the beginning, deleted/recreated a couple times, and now I'm also been struggling to get the /dist to auto-create (yes, i created a new js and scss file, no change.) i also did a non-destructive edit to existing js and scss files to force a save, but its just stuck and wont compile anymore. this app has so much promise. I just can't get it to work! arrrgh. I've got a lot of learning to do.

**Comment by clancyjr** [comment]
I think i figured it out. when you're creating the spotify app on the developers site, you need to add "http://localhost:8888/callback" in the "callback" section. this basically tells the app "hey look at the local device for the next step". or something like that. either way, it helped.
