### ISSUE TITLE
Node/Node Sass Out of Date

### ISSUE THREAD

**Issue by dgorbunov** [jonashcroft/Nowify#20]
Project cannot compile on latest version of Node and Node-Sass. It seems in order to build the project, an older version of Node Sass has to be used, there is a conflict in `src/styles/global/reset.scss` that requires Node-Sass version 4, but that means Node also has to be downgraded.

This is not in the docs anywhere, is there a specific version of Node and Node-Sass that has to be used
?

**Comment by dgorbunov** [comment]
Update: I've gotten it to build.
Node-Sass 4.14.1 must be installed with this command:
`yarn add node-sass@4.14.1`
And any 14.x Node version will work. I recommend using nvm to switch your node version:
`nvm install 14.0.0'
'nvm use 14.0.0'

Might be nice to add this to the docs.

**Comment by jonashcroft** [comment]
Hey @dgorbunov ,

I'm glad you found the cause of this! `node-sass` always seems to be problematic for these sorts of problems. It would be great if you could share what the conflict in `src/styles/global/reset.scss` was? (Or open a PR!)

Happy to add to the README.

Thanks!

**Comment by jonashcroft** [comment]
Resolved on latest update.

* Updated local node-sass
* Set environment parameter for Node 14 to allow Netlify build

Thanks!
