### ISSUE TITLE
Another case of 'INVALID_CLIENT: Invalid client'

### ISSUE THREAD

**Issue by ianaitch** [jonashcroft/Nowify#28]
Hi, 

I'm kind of new to some of this, so I may have made a dumb error. 

I forked Nowify, deployed into Netlify, set up the spotify developer app, copied the client id and secret environment variables into Netlify environment settings. Also copied the URL of my app in Netlify into the redirect URI in the Spotify app. When I go to the Netlify URL I see the correct page 
![image](https://user-images.githubusercontent.com/5603036/148082463-69393ce5-c402-4b03-9b75-4f085260a4d3.png)
But every time I get this error after clicking login :-
![image](https://user-images.githubusercontent.com/5603036/148082540-59a6af09-4783-42d0-9784-c57c8bbd0347.png)

It looks like I log in, authenticate and then fail.

The URL returned from Spotify is "https://accounts.spotify.com/authorize?client_id=undefined&response_type=code&redirect_uri=https%3A%2F%2F<the correct address here>.netlify.app&state=uecd1nl93p6-o8fv91wagf-q3nxdwgkp-fsqelse9&scope=user-read-currently-playing

I looked at the other two issues where Invalid Client was mentioned and neither seemed to give a clue. Any ideas what I missed? I see that Client_Id is blank in the URL above.

All help always gratefully received!

**Comment by ianaitch** [comment]
(Yeah, the editor here just fiddled with my URL shown above because I tried to replace my URL with <other text>. The &redirect_uri I see in the URL is correct, and has the right text before .netlify.app).

**Comment by ianaitch** [comment]
The correct URL is : https://accounts.spotify.com/authorize?client_id=undefined&response_type=code&redirect_uri=https%3A%2F%2Fmynowify.netlify.app&state=vk8dt2cuub-rvqe1jg42f-0m4c6fqsj-77mjdsyd&scope=user-read-currently-playing
This is what errors.

**Comment by Dherdre** [comment]
Hi,

Did you already found a fix?
I have the same problem.

Thanks in advance!

**Comment by JannisBluu** [comment]
Hey, I have the same problem. May you can help not only one, but directly two, who searches for help ;D

Best regards

**Comment by jonashcroft** [comment]
Hey! Sorry you've been having trouble with this.

A similar issue was mentioned in #27.

Are any of you able to confirm if this persists after redeploying when you add your keys in?

**Comment by Dherdre** [comment]
Hi,

That did the trick!
Thank you!

**Comment by JannisBluu** [comment]
At first thanks for the fast support 🥇 
Now I have the error message 

INVALID_CLIENT: Invalid redirect URI 

after clicking on the Log In Button.
I´ve added the client key and secret to netflify an deployed it as you describe in #27

Thanks in advance!

**Comment by jonashcroft** [comment]
That error means that your redirect URI is incorrect. 

You need to add the URL of your app within [My Applications](https://developer.spotify.com/dashboard/login) on Spotify. This is described in the instructions in the dashboard.

The URI must match your own apps URl exactly.

**Comment by JannisBluu** [comment]
Thank you, now it works. I deleted the uri in spotify and copyed it again, now it works. ♥

**Comment by jonashcroft** [comment]
Great! Thank you. Closing this.
