### ISSUE TITLE
[Request] Add Licensing Documentation

### ISSUE THREAD

**Issue by KeshavChawla** [jonashcroft/Nowify#41]
Is it possible to add a licensing file to this project or get some clarity as to what the appropriate licensing is? My intended use case is to create a non-commercial derivative work for personal use but the added clarity to this sure would help!

**Comment by jonashcroft** [comment]
Yikes, sorry it's taken me so long to reply to this!

I can look to add some official licensing to the repo for sure. I'm not entirely sure off the top of my head which one it'll be but I imagine it'll be one of the standard ones as you mentioned.

**Comment by jonashcroft** [comment]
Hey @KeshavChawla 

I've now added licensing to the repo - just gone with MIT as that seems the most reasonable.

Thanks for raising this.

**Comment by KeshavChawla** [comment]
Thanks @jonashcroft appreciate it!
