### ISSUE TITLE
Can you help

### ISSUE THREAD

**Issue by racer122** [jonashcroft/Nowify#5]
Hey im trying to get this downloaded to my pi but i dont get it can you help maybe?

**Comment by clancyjr** [comment]
the "work" of the app is all done on a mac or windows box. then when you run the "gulp" command, it compiles the app down to a couple simple files that appear in a "/dist" folder. copy that dist folder and the index.html file to the pi. I'm still struggling to get it to work myself, but I've gotten that far at least once or twice.
