### ISSUE TITLE
Raspberry Pi Usage

### ISSUE THREAD

**Issue by TellTej** [jonashcroft/Nowify#6]
I don't fully understand how to install gulp and this library onto my pi. Could you help?

**Comment by clancyjr** [comment]
You dont install gulp and the library on the pi. you do nvm/node/gulp tasks on your computer, that compiles the code into the /dist folder, and you copy the /dist folder (and the index.html) to the pi. then have the index file auto-open on the pi.

**Comment by jonashcroft** [comment]
As above - compile the code on your computer first, then move things over.

I'm actually in the middle of rewriting this whole thing to be more modern and easier, it should be ready for use in about a week 🙂

**Comment by jonashcroft** [comment]
2.0.0 released! "about a week" was definitely ambitious
