### ISSUE TITLE
cannot get it to compile (gulp)

### ISSUE THREAD

**Issue by clancyjr** [jonashcroft/Nowify#7]
because i was getting the invalid URI error (after getting a successful compile), I went back to the beginning, deleted/recreated. But now I'm struggling to get the /dist to auto-create when running gulp. 

yes, i created a new js and scss file, no change. 
i also did a non-destructive edit to existing js and scss files to force a save, but it just seems to be stuck and wont compile the /dist anymore. 

this app has so much promise. I just can't get it to work! arrrgh. I've got a lot of learning to do i guess.

**Comment by jonashcroft** [comment]
Hey!

I'm sorry to see that you can't get it to compile. Can you send any logs of what errors you see when you try?

I'm actually in the middle of rewriting this whole thing to be more modern and easier, it should be ready for use in about a week 🙂

**Comment by jonashcroft** [comment]
2.0.0 released!
