### ISSUE TITLE
User authentication and permissions

### ISSUE THREAD

**Issue by hifarrer** [jonashcroft/Nowify#8]
Hi, there.
I was wondering how the user authentication will work on this.
If I were to give this to my mom, would she still need to login and approve app permissions on the Pi?

**Comment by jonashcroft** [comment]
Hey!

This currently uses Implicit Consent - this means that you would need to re-sign in to Shopify every time you load this up.

The flow generally goes:

1) "Click here to authenticate with Spotify"
2) User is redirected to Spotify, they press 'Approve this app'
3) User is redirected back to app, their current audio is displayed

I'm currently testing a 2.0 of Nowify this which utilises oAuth, which will ensure the auth is maintained. I expect this'll be out in the next fortnight.

**Comment by hifarrer** [comment]
Thanks, That would be awesome!

**Comment by jonashcroft** [comment]
2.0.0 released. "the next fortnight" may have been ambitious!
